#include "esp_wifi.h"
#include "esp_event.h"
#include "esp_bt.h"
#include "esp_bt_main.h"
#include "esp_gap_ble_api.h"
#include "esp_gatts_api.h"
#include "esp_gattc_api.h"
#include "mqtt_client.h"
#include "lwip/sockets.h"
#include "lwip/netdb.h"
#include "esp_http_client.h"
#include "esp_http_server.h"
#include "driver/gpio.h"
#include "driver/adc.h"
#include "driver/i2c.h"
#include "driver/spi_master.h"
#include "driver/uart.h"
#include "esp_tls.h"
#include "esp_crt_bundle.h"
#include "nvs.h"
#include "nvs_flash.h"

void app_main() {}